### ISSUE TITLE
work with latest node.js v6.4.0?

### ISSUE THREAD

**Issue by cho6955** [PacktPublishing/Modern-JavaScript-Applications#1]
I am trying to follow along the book code sample on chapter 1 and 2 but I am getting strange errors as 

```
1. > Chapter 1/seneca-example$ node main.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'parambulator'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/erp/workspace/sample/Modern-JavaScript-Applications/Chapter 1/seneca-example/node_modules/seneca/seneca.js:25:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

```
2. Chapter 2/Final/config-service$ node app.js 
module.js:457
    throw err;
    ^

Error: Cannot find module './norma-parser'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/erp/workspace/sample/Modern-JavaScript-Applications/Chapter 2/Final/config-service/node_modules/seneca/node_modules/norma/norma.js:19:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

I am using node.js v6.4.0.  Any idea why I am getting such errors?

**Comment by techsachinkumar** [comment]
Hi cho6955

Did you try installing all the dependency files?
Try npm install and check to see if your facing issues or manually install the missing modules through it.
Eg. npm install "missing module name"

Regards
